title = "Dex"
disableKinds = ["taxonomy", "taxonomyTerm"]
copyright = "Cloud Native Computing Foundation"

enableGitInfo = true

[markup.highlight]
style = "paraiso-dark"

[params]
font_awesome_version = "5.12.0"
description = "A Federated OpenID Connect Provider"
favicon = "favicon.png"
repositoryUrl = "https://github.com/dexidp/website"
contentDir = "/content/"

[params.logos]
navbar = "dex-horizontal-color.png"

[[params.social]]
name = "Twitter"
color = "#00aced"
url = "https://twitter.com/CloudNativeFdn"
icon = "fab fa-twitter"

[[params.fonts]]
name = "Fira Sans"
sizes = [300, 400, 600, 700]
type = "sans_serif"

[[params.fonts]]
name = "Fira Mono"
sizes = [300, 400, 600, 700]
type = "monospace"

[[params.fonts]]
name = "Fire Sans"
sizes = [100, 200, 300, 400, 500, 600, 700]
type = "heading_font"

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CNCF"
url = "https://cncf.io"
weight = 2

[[menu.main]]
name = "Getting Started"
url = "/docs/getting-started/"
weight = 3

[[menu.main]]
name = "Documentation"
url = "/docs/"
weight = 3
